'use strict';
const assert = require('node:assert/strict');
const vscode = require('vscode');
async function run() {
  const extension = vscode.extensions.getExtension('mundane-engineering.mundane-requirements');
  assert.ok(extension, 'extension is installed in actual host');
  const api = await extension.activate();
  await new Promise(resolve => setTimeout(resolve, 350));
  const result = await api.validate();
  assert.equal(result.length, 1);
  assert.equal(result[0].result.protocol, 'mundane-editor-0.1');
  const doc = await vscode.workspace.openTextDocument(vscode.Uri.joinPath(vscode.workspace.workspaceFolders[0].uri, 'parent.mreq.yaml'));
  assert.equal(doc.languageId, 'mundane-requirements');
  assert.equal(result[0].result.valid, true);
  const child = await vscode.workspace.openTextDocument(vscode.Uri.joinPath(vscode.workspace.workspaceFolders[0].uri, 'child.mreq.yaml'));
  const original = child.getText();
  async function replace(document, text) {
    const edit = new vscode.WorkspaceEdit();
    edit.replace(document.uri, new vscode.Range(document.positionAt(0), document.positionAt(document.getText().length)), text);
    assert.ok(await vscode.workspace.applyEdit(edit));
  }
  await replace(child, original.replace('PARENT', 'MISSING'));
  await api.validate();
  assert.ok(vscode.languages.getDiagnostics(child.uri).some(d => d.code === 'dangling-reference'));
  const first = api.validate();
  await replace(child, original);
  await first;
  await api.validate();
  assert.equal(vscode.languages.getDiagnostics(child.uri).length, 0, 'new buffer clears errors and supersedes stale request');
  assert.equal(require('node:fs').readFileSync(child.uri.fsPath, 'utf8'), original, 'validation never saves the buffer');
  await replace(child, 'format: [\n');
  await api.validate();
  assert.ok(vscode.languages.getDiagnostics(child.uri).length);
  await replace(child, original); await api.validate();
  const referencePoint = () => child.positionAt(child.getText().lastIndexOf('PARENT') + 1);
  const definitions = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', child.uri, referencePoint());
  assert.equal(definitions.length, 1); assert.equal(definitions[0].uri.fsPath, doc.uri.fsPath);
  assert.equal(doc.getText(definitions[0].range), '"PARENT"');
  await replace(doc, '\n' + doc.getText());
  const moved = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', child.uri, referencePoint());
  assert.equal(moved[0].range.start.line, definitions[0].range.start.line + 1, 'unsaved target origin moves');
  await replace(doc, doc.getText().substring(1));
  await replace(child, original.replace('id: "CHILD"', 'id: "PARENT"'));
  assert.equal((await vscode.commands.executeCommand('vscode.executeDefinitionProvider', child.uri, referencePoint())).length, 0, 'duplicate target is never selected');
  await replace(child, original.replace('"PARENT"', '"MISSING"'));
  assert.equal((await vscode.commands.executeCommand('vscode.executeDefinitionProvider', child.uri, child.positionAt(child.getText().lastIndexOf('MISSING') + 1))).length, 0);
  await replace(child, original.replace('The storage shall', 'PARENT says the storage shall'));
  assert.equal((await vscode.commands.executeCommand('vscode.executeDefinitionProvider', child.uri, child.positionAt(child.getText().indexOf('PARENT') + 1))).length, 0, 'prose is not a reference');
  await replace(child, original);
  const savedParent = doc.getText();
  await replace(doc, 'format: "mundanereq-yaml-0.3"\nrequirements: [{title: "😀 measurements", id: "PARENT", statement: "The logger shall retain measurements."}]\n');
  const unicode = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', child.uri, referencePoint());
  assert.equal(doc.getText(unicode[0].range), '"PARENT"', 'non-BMP prefix maps to exact UTF-16 target');
  await replace(doc, savedParent);
  console.log('PASS actual definition provider: cross-file origins, unsaved target moves, duplicate/missing targets and prose exclusion');
  const eol = new vscode.WorkspaceEdit(); eol.set(child.uri, [vscode.TextEdit.setEndOfLine(vscode.EndOfLine.CRLF)]);
  assert.ok(await vscode.workspace.applyEdit(eol));
  assert.ok(child.getText().includes('\r\n'));
  await replace(doc, 'format: [\n');
  assert.equal(((await vscode.commands.executeCommand('vscode.executeFormatDocumentProvider', child.uri, {tabSize:2, insertSpaces:true})) || []).length, 0, 'invalid surrounding project blocks edits');
  await replace(doc, savedParent);
  await vscode.window.showTextDocument(child);
  await vscode.commands.executeCommand('editor.action.formatDocument');
  assert.equal(child.getText(), original, 'LF conversion preserves every other authored byte');
  assert.equal(((await vscode.commands.executeCommand('vscode.executeFormatDocumentProvider', child.uri, {tabSize:2, insertSpaces:true})) || []).length, 0, 'formatting is idempotent');
  assert.equal(require('node:fs').readFileSync(child.uri.fsPath, 'utf8'), original);
  console.log('PASS actual formatting provider: whole-project validation, CRLF-to-LF edits, exact preservation, idempotence and no save');
  const selection = await vscode.workspace.openTextDocument(vscode.Uri.joinPath(vscode.workspace.workspaceFolders[0].uri, 'editor.json'));
  const selectionText = selection.getText();
  const schema = await vscode.workspace.openTextDocument(vscode.Uri.joinPath(vscode.workspace.workspaceFolders[0].uri, 'schema.json'));
  const schemaText = schema.getText();
  const parentText = doc.getText();
  const withAttributes = text => text.replace('mundanereq-yaml-0.3', 'mundanereq-yaml-0.4')
    .replace('requirements:', 'attributeSchema: "logger-metadata"\nrequirements:') + '    attributes:\n      discipline: "software"\n';
  await replace(selection, JSON.stringify({format:'mundane-editor-project-0.1', source:'yaml-0.4', files:['parent.mreq.yaml','child.mreq.yaml'], attributeSchema:'schema.json'}));
  await replace(doc, withAttributes(parentText)); await replace(child, withAttributes(original));
  assert.equal((await api.validate())[0].result.valid, true);
  await replace(schema, schemaText.replace('"software"', '"firmware"'));
  await api.validate();
  assert.ok(vscode.languages.getDiagnostics(child.uri).some(d => d.code === 'attribute-value'));
  await replace(schema, '{\n'); await api.validate();
  assert.ok(vscode.languages.getDiagnostics(schema.uri).some(d => d.code === 'attribute-schema-invalid'));
  await replace(schema, schemaText);
  const attrText = withAttributes(original);
  const complete = point => vscode.commands.executeCommand('vscode.executeCompletionItemProvider', child.uri, point);
  await replace(child, attrText + '      ow\n');
  const names = await complete(child.positionAt(child.getText().lastIndexOf('ow') + 2));
  assert.deepEqual(names.items.filter(i => i.detail?.startsWith('text')).map(i => i.label), ['owner-team']);
  assert.ok(names.items.some(i => i.insertText === 'owner-team: '));
  assert.ok(!names.items.some(i => i.label === 'discipline'), 'used names are omitted');
  await replace(child, attrText.replace('"software"', ''));
  const enums = await complete(child.positionAt(child.getText().indexOf('discipline:') + 'discipline: '.length));
  assert.deepEqual(enums.items.filter(i => i.detail?.startsWith('enum')).map(i => i.label).sort(), ['electronics','mechanical','software']);
  assert.ok(enums.items.some(i => i.insertText === '"software"'));
  await replace(child, attrText.replace('The storage shall', 'owner-team says the storage shall'));
  assert.ok(!(await complete(child.positionAt(child.getText().indexOf('owner-team') + 3))).items.some(i => i.detail?.includes('(optional)')));
  await replace(child, attrText + '      # ow\n');
  assert.ok(!(await complete(child.positionAt(child.getText().lastIndexOf('ow') + 2))).items.some(i => i.detail?.includes('(optional)')));
  await replace(child, attrText + '      ow\n');
  await replace(schema, schemaText.replace('owner-team', 'responsible-team'));
  assert.ok(!(await complete(child.positionAt(child.getText().lastIndexOf('ow') + 2))).items.some(i => i.label === 'owner-team'));
  await replace(schema, schemaText);
  console.log('PASS actual completion provider: repaired partial keys, used names, quoted enums, prose/comments and unsaved declarations');
  await replace(selection, selectionText);
  await replace(doc, parentText); await replace(child, original); await api.validate();
  assert.equal(vscode.languages.getDiagnostics(schema.uri).length, 0);
  console.log('PASS unsaved declaration changes, enum diagnostics and schema repair');
  console.log('PASS unsaved syntax/reference diagnostics, repair, stale request rejection and unchanged disk');
  console.log('PASS actual VS Code Extension Host: activation, language registration, explicit project and Java bridge');
}
module.exports = { run };
